---
Name: mysite
After: 'framework/*','cms/*'
---
SSViewer:
  theme_enabled: false

MySQLDatabase:
  connection_charset: 'utf8'

GDBackend:
  default_quality: 90

SiteTree:
  nested_urls: true
  # Disable creating of default pages (like home) on /dev/build
  # create_default_pages: false

Email:
  admin_email: 'email@mysite.com'

LeftAndMain:
  cms_highlight_colour : '#23282d'
  cms_success_color : '#0073aa'
  cms_error_color : '#d54e21'
  cms_style_tinymce: true

ColorField:
  colors:
    - '#000'
    - '#FFF'
SVGTemplate:
  base_path: mysite/dist/images/svg
