---
Name: mysite
After: 'framework/*','cms/*'
---
SSViewer:
  theme_enabled: false

MySQLDatabase:
  connection_charset: 'utf8'

GDBackend:
  default_quality: 90

Image:
  force_resample: true

SiteTree:
  nested_urls: true

LeftAndMain:
  cms_highlight_colour : '#23282d'
  cms_success_color : '#2962ff'
  cms_error_color : '#d54e21'
  cms_style_tinymce: true

ColorField:
  colors:
    - '#000'
    - '#FFF'

SVGTemplate:
  base_path: mysite/dist/images/svg

#FormSpamProtectionExtension:
#  default_spam_protector: NocaptchaProtector
#NocaptchaField:
#  site_key: ''
#  secret_key: ''
#  verify_ssl: false

---
Only:
  environment: dev
---
Email:
  admin_email: 'email@mysite.com'
---
Except:
  environment: dev
---
Email:
  admin_email: 'email@mysite.com'
